name: 'docker-build-and-publish'
description: 'Builds docker images and publish them on request'
author: "Jeroen Knoops <jeroen.knoops@philips.com>"
branding:
  icon: "anchor"
  color: "gray-dark"
inputs:
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  image-name:
    description: 'The name of the image'
    required: true
  tags:
    description: 'String with tags, separated by a space'
    required: true
  push-branch:
    description: 'Specifies branch to push, separated by a space - DEPRECATED - Will be replaced by push-branches'
  push-branches:
    description: 'Specifies branches to push, separated by a space'
    default: 'master main'
  base-dir:
    description: 'Base directory to perform the build'
    default: '.'
  slsa-provenance:
    description: 'Create SLSA Provenance json'
    required: false
  github_context:
    description: 'internal (do not set): the "github" context object in json'
    required: true
    default: ${{ toJSON(github) }}
  runner_context:
    description: 'internal (do not set): the "runner" context object in json'
    required: true
    default: ${{ toJSON(runner) }}
outputs:
  container-digest:
    description: 'Container digest. Can be used for generating provenance and signing.'
  container-tags:
    description: 'Container tags. Can be used for generating provenance and signing.'
  push-indicator:
    description: 'Is set to true when containers have been pushed to the container repository'
  slsa-provenance-file:
    description: 'SLSA provenance file if created'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dockerfile }}
    - ${{ inputs.image-name }}
    - ${{ inputs.tags }}
    - ${{ inputs.push-branches }}
    - ${{ inputs.base-dir }}
    - ${{ inputs.push-branch }}
  env:
    SLSA_PROVENANCE: ${{ inputs.slsa-provenance }}
    GITHUB_CONTEXT: ${{ inputs.github_context }}
    RUNNER_CONTEXT: ${{ inputs.runner_context }}
