name: 'Action docs'
on:
  push:
    branches:
      - main
      - develop
    pull_request:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # ratchet:actions/checkout@v3
      - uses: npalm/action-docs-action@1ae674557116c26e42a4b278d8d49f0a25a4d670 # ratchet:npalm/action-docs-action@v1.3.0
      - name: Update readme in the repository
        if: github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@0b007fbd1180b8e3a3668b21c6517392fe8f26eb # ratchet:stefanzweifel/git-auto-commit-action@v4.15.4
        with:
          commit_message: "chore(ci): Updating readme"
          file_pattern: README.md
