name: Shell linter 

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint check
        uses: azohra/shell-linter@v0.6.0
        with:
          exclude-paths: "bin/install_cosign.sh"
